### PR TITLE
Added libusb hotplugging

### PR DESCRIPTION
**Pull request by viktorgino**
Added a new thread for polling libusb events and callbacks for new device notification. Implemented basic handling for the desktop specific code.

### CODE REVIEW

**Comment by lmagder** [comment]
Hi @viktorgino I appreciate you taking a look at this, but I'm not sure the way this is structured this is the right approach. As I see it, the two main objectives I think the code needs to accomplish with the hotpluging are

- Waiting for a new device if no suitable device is found without burning CPU
- Avoiding the hardcoded sleep while waiting for the device re-connection after switching to AAP mode.

Because of this I think this code could be simplified a lot by containing the entire logic inside HUTransportStreamUSB::Start() since at least for my use case it's fine if HUTransportStreamUSB::Start() blocks forever if there is no device. This would allow it to reuse the same libusb context and also avoid needing to create and synchronize other threads. Maybe something like this pseudo-code

```
def tryDevice(device):
    test device for ACC
    if found AAC:
        wait for hotplug of VEN_ID_GOOGLE, DEV_ID_OAP/DEV_ID_OAP_WITH_ADB with some timeout
        if not timedout:
            return success, start AA

def HUTransportStreamUSB::Start():
    foreach usb device:
        tryDevice()

    loop while not connected:
         wait for hotplug of new device (any IDs)
         tryDevice(newDevice)
```

There is also the issue that at least with V55 of the car os there is only libusb v1.0.9 and the hotplug interface did not arrive until 1.0.16 :cry: so while it is clearly a good idea to use the libusb interface if it's available, the code needs to have a fallback to a Linux-specific method that works on kernel 3.0.35 or older. What that is exactly, I'm not sure yet.

I know that's a really drastic change from what you have, but my eventual goal here is having this run as a background service on the car OS to replicate a real headunit more closely and support partial audio/video focus.

**Comment by lmagder** [comment]
I did some digging and it looks like libudev is available specifically 0.11.2, not as a nice an API, but apparently it can do it using the monitor API http://ftp.kernel.org/pub/linux/utils/kernel/hotplug/libudev/libudev-udev-monitor.html

**Comment by viktorgino** [comment]
@lmagder what do you think about [1283bb1](https://github.com/gartnera/headunit/pull/37/commits/1283bb1a09c7acde8335e4b8a754ed76dd2417bc)?

**Comment by lmagder** [comment]
Great. Thanks for updating based my feedback. I will resolve the conflicts and merge

**Comment by lmagder** [comment]
Thanks. This pull request has been integrated manually.

**Pull request merged**
