### PR TITLE
uninstaller script for AA

### PR DESCRIPTION
**Pull request by mishaaq**
This commit adds uninstaller script which is an opposite to existing installer script. It tries to revert all changes in CMU made by the installer, but does NOT remove installation using AIO.

Additionally I've fixed some syntax problems in JS code.

### CODE REVIEW

**Comment by lmagder** [comment]
Thanks for the PR~ This is something I had on my list to do before the next release, so one less thing on my list 👍 

I think your uninstallation steps look correct (although I haven't tested) but what do you think about integrating this into the installer to reduce code duplication? Maybe it could detect an existing install and offer to reinstall/upgrade or remove it?

Or is there a specific reason you split it out which I haven't thought about?

**Comment by mishaaq** [comment]
Yes, I know this is a massive amount of code duplication and should be reorganised. I want to have a quick uninstaller though.

I've never been a shell scripting language enthusiast (bash or similar) :) and I'm curious about developing a big scripts doing many things using this tool. I mean, it has some awkward traits that I prefer to write scripts with python/ruby, but AFAIK no one compiled the interpreters for i.mx6.

No matter what you're right - it would be better to keep the code base minimal. I'll try to prepare a tool for installation/upgrade and deinstallation.

**Comment by mishaaq** [comment]
@lmagder I've updated the script and add support for uninstallation and updating. I've tested it on chroot-ed environment and it should behave as expected, but could you take a look at it and catch some "bash" nuances before I'll test it in my car? :)

**Comment by lmagder** [comment]
Sure, I will take a look more closely. To be honest I am usually a Windows guy so probably the worst person to check for "bash nuances" 😆 but I'll try and verify it. Just from a quick reading: It might make the script easier to follow if you defined install and remove functions you called from logic around if [ ${remove} -eq 1 ]; then instead of inling everything since the bash if syntax is kind of weird to my eyes and it would be easy to miss the end of the block.

**Comment by mishaaq** [comment]
I've cleaned up the installer and grouped standalone statements into functions. Hope it helps.

**Pull request merged**
