### PR TITLE
Use unused MLENT stream

### PR DESCRIPTION
**Pull request by Trevelopment**
I have done it!!! I looked through all the sound configuration file and I noticed an unused stream that was fully set up with its own alsa device, MLENT.  By using that stream, AA is now on its own stream and it solves most of the sound focus issues (or at least makes them easier to fix)

### CODE REVIEW

**Comment by Trevelopment** [comment]
@lmagder It turns out the streams are hard coded into the config files you may be able to add more but l found one that was set up and not used. I think they were going to use the MLENT stream for AA and CP when they were still planning to release them.  the ML is for mirrorlink.

**Comment by lmagder** [comment]
Awesome! Great find. Works as far as I can tell and doesn't mess with the built-in media player.

**Comment by EQMOD** [comment]
Nice !! ;) How do you guys debug your setup ? Do you have a separate cmu board or directly on the car  ? :)

**Comment by Trevelopment** [comment]
@EQMOD Well I do have a separate external CMU (built for me by Modfreakz) buuuut its not hooked up to any speakers so i cant test this particular issue (or the bluetooth calls issue before) with that unit... I can only use my car.

**Pull request merged**
