### PR TITLE
fix for screen corruption with backup camera

### LINKED ISSUE #48: screen corrupts when backup camera turns on
I've compiled and installed current HEAD version (commit [d0706eab21dbac9fca2ca3c967ded59e9faf1da6](https://github.com/gartnera/headunit/commit/d0706eab21dbac9fca2ca3c967ded59e9faf1da6)). When going reverse the screen goes corrupt - it displays something like a combination of two surfaces: the camera and Android Auto. Probably the headunit should "release" the screen somehow or TV_TOUCH_SURFACE is not the right one?

### PR DESCRIPTION
**Pull request by mishaaq**
Fixes #48. As AA and backup camera share the same TV_TOUCH_SURFACE we need to stop video output and leave the surface when backup camera kicks in.

### CODE REVIEW

**Comment by mishaaq** [comment]
Quick fix made following comments from the issue. Tested and correctly leaves the screen for backup camera - no more corruption :). There is one thing only: when leaving reverse the CMU changes surface to JCI_OPERA_PRIMARY and headunit doesn't respond on this. When the AA appeared on screen after phone connection (not using Apps entry) we end on last opera "window". Entering AA manually afterwards fixes the problem as CMU returns to our application and video focus is restored.

**Comment by mishaaq** [comment]
Tested in my car and corruption went away. There is only a problem with leaving reverse - the surface goes to last opera "window" instead of returning to AA. Not sure why. I have some ideas:
1. BUCPSAClient#DisplayMode gets another non 0 value in parameter currentDisplayMode therefore we are actually change the surface to JCI_OPERA_PRIMARY
2. There is something like race-condition: we are returning to AA, but CMU changes the surface a little bit later.
3. I've made a little mistake and cannot notice it.

**Comment by lmagder** [comment]
Cool, this looks like a good start. I like the addition of the enum, it makes sense. However you might want to define it as an "enum class" if you want to use the :: syntax.

I think I know the reason for the failure on resume (and also the crash) and it's my fault 😃 BUCPSAClient is a member of VideoOutput so when you call VideoFocusHappened(false) this actually deletes VideoOutput so BUCPSAClient is destroyed so it's in a weird state. It might make sense to move the BUCPSAClient instance to MazdaEventCallbacks instead however that require checking the state of video focus (probably via videoOutput != 0) when the backup camera engages to know if the code should take focus again when it's done otherwise going into backup camera would start AA randomly.

**Comment by mishaaq** [comment]
Ok. At last I've managed to find out that CMU was changing surface to JCI_OPERA_PRIMARY in the background after switching off backup camera (despite having TV_TOUCH_SURFACE requested before), so it looks like I had a good presumption about some race condition. That's why I've delayed creating video output and switching the surface by a second. It was a lucky shot - 100 ms was too early. I would have stopped with this value - cutting it more may introduce some random failures.

I've tested it on my car: it works well even when starting AA with backup camera already on. I hope you find the code ready to merge :).

**Comment by lmagder** [comment]
Great! thanks. It looks good from the diff, but I want to test it out on my car to make 100% sure before I merge. Hopefully I have a chance this week, since with this an your installer stuff I think we might be near a release

**Comment by lmagder** [comment]
Thanks. This pull request has been integrated manually.

**Pull request merged**
