### PR TITLE
Use all the Mazda buttons!

### LINKED ISSUE #62: Log display is broken
The code in [_androidautoApp.js](https://github.com/gartnera/headunit/blob/master/mazda/installer/config/androidauto/jci/gui/apps/_androidauto/js/_androidautoApp.js) should be reading the log file written to /tmp/mnt/data/headunit.log as reported by the status results but something isn't working.

### PR DESCRIPTION
**Pull request by Trevelopment**
### OK Cool
A while ago I found this little mini handheld wireless keyboard and just so I wouldn't lose it and not even thinking  it would work, I put the dongle in the USB slot and I pressed G and it triggered the voice command function.  I proceeded to map all the keys that worked and put it on a note in my phone knowing I would eventually use it for something.  Here is an interesting one volume knob up/down = a/s so if we want we can override that bitch too haha. 
So I decided to try getting video focus back by pressing the nav button.  And it works with little effort BUT when the call is over guess what... contextChange! then we lose video focus again but press the nav button and  your back in AA like nothing happened.  The next step would be to find what the bthfState of "start call" and "end call" and when I thought of that the other day thats when it hit me and I understood protobuf so if I'm not mistaken we want to make something like `message CallStatus`  with `enum BthfState` then the entries are the different states which we know `BTHF_STATE_IDLE = 0`  then, I already tried this but I dont remember exactly the other numbers, SSH in into your car and run `testapp_bthf` and make some calls and it shows you the states of all the bthf variables (the ones in CallStatus you can actually see any of the signals from the BTHF class) and note the state on `IncomingCall` or `ActiveCall`  or whatever we need to hook into.

Also: 
- Fav button brings you to the AA home screen 
- phone button to the phone screen
- and phone buttons work to answer and end calls too.

And I added the Android Auto Icon for fun so it doesn't use the default icon when you open it.
and fix #62

### CODE REVIEW

**Comment by Trevelopment** [comment]
```
message CallStatus
{
  enum BTHF_STATE
  {
    BTHF_STATE_IDLE = 0;
    BTHF_STATE_INCOMING = 1;
    BTHF_STATE_ACTIVE = 2;
    BTHF_STATE_END = 3;
  }
  required BTHF_STATE bthf_state = 1
}
```
Does that look right?

**Comment by lmagder** [comment]
Thanks for the work on this! Hopefully I can take a deeper look to review and test this weekend. 

Just after a quick glance I noticed there are a lot of unrelated whitespace changes. I'm all for fixing formatting problems, but if that's not the case, can you try and revert them where possible? It makes the diff kind of noisy and harder to see where the actual changes are when looking at the history. Thanks!

**Comment by Trevelopment** [comment]
Um OK sure but I am just trying to get rid of all that trailing white space for that exact reason.  Removing the trailing white space is a good coding convention and will allow for future diffs to have less noise due to them especially from me since I use Atom for a code editor so when I save a file it automatically removes trailing white space. In fact all I did to remove all that was open each file and save it.  The actual changes in this pull request are actually minimal all I did was fix up the HUIBs, add to the switch where the input keys are defined, added the AA an icon, and change that one line in AAlogPoll.  How about I go through and make sure its all removed from every file and make that one commit, would that be better?

**Comment by Trevelopment** [comment]
@lmagder  See even when reverting the last commit where I fix the trailing white space the in commits before each file I edit has all that noise because of it and I don't want to revert that far you know its unnecessary. I mean I saw your not blog I would think you'd be all about them good coding conventions dogggg.

**Comment by lmagder** [comment]
No problem, yeah I agree the whitespace of these files is bad and all over the place, not just trailing whitespace. I didn't notice you were fixing the trailing spaces, I thought it was just random edits due to changing stuff and then removing it in the editor. I think ideally a whitespace-only change to fix all this is the best but there's no need to make this PR all messed up just to conform to my OCD 😛 (Plus if you examine the history of my changes you will see I have done the same thing of reformatting files while doing other edits...whoops)

**Comment by Trevelopment** [comment]
haha right I agree it is a lot easier to see what I changed for this PR now, all good changes too I think you will be pleased with them

**Comment by lmagder** [comment]
Great, looks good! I tested it and everything seems to work fine. The log is still broken for me despite your fix to `_androidautoApp.js` but it was broken before so it's not a regression :smile:

**Comment by Trevelopment** [comment]
Wait what its still broken? I tested it and it works! Did you tap the text box it takes a few seconds to load.

**Comment by lmagder** [comment]
Yeah I tried tapping a few times, since I noticed you added the onclick handler but still nothing loaded. I dunno. I'm also open to other ways of displaying the log if you can think of any. I guess it could read it though a websocket call from a buffer in the headunit process but then it wouldn't display when the process crashed, which is when you most want to view it.

**Comment by Trevelopment** [comment]
Well Im guessing you haven't used AIO but I made an AIO Tweaks App and in it you can start and stop the headunit process at will and view the log in a pop up window

**Comment by Trevelopment** [comment]
https://github.com/Trevelopment/MZD-AIO/releases/tag/v2.7.0

**Comment by Trevelopment** [comment]
And when you start the headunit process inside AIO the stdout prints in a pop up as well

**Comment by Trevelopment** [comment]
with $(whtever).prepend() so you can always see the next line because javascript scrolling functions for some reason don't work correctly in that version of opera

**Pull request merged**
