### PR TITLE
Hud units

### PR DESCRIPTION
**Pull request by VitaliyKurokhtin**
- Tracking HandleNaviStatus for stop signal to clear HUD when navigation finishes or canceled.
- Displaying Straight icon for merge without direction. Seems fitting and better than not not showing anything.
- Displaying HUD distance in units reported by AA.

### CODE REVIEW

**Comment by rolanie3** [comment]
How can I build and test this merge without using the AIO software? I have VS2016 installed, can I do it from the source?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by VitaliyKurokhtin** [comment]
@rolanie3 I've used instructions by @Trevelopment from here https://mazdatweaks.com/androidauto/. Except I'm using Windows Subsystem for Linux instead of VM to run Ubuntu 16.04. Once build script completes you're left with headunit executable that you can copy over existing one to your CMU in any way you like. Replacing one in files generated by AIO works fine as well.

**Comment by m3us** [comment]
Installed ubuntu 16.04 through windows as @VitaliyKurokhtin suggested. Compiled as per 
```
cd ~
sudo apt-get update
sudo apt-get install git adb bluetooth libbluetooth-dev tlp blueman bluemon bluez libsdl2-2.0-0 libsdl2-ttf-2.0-0 libportaudio2 gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-alsa
sudo apt-get install libssl-dev libusb-1.0-0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libsdl1.2-dev libgtk-3-dev libudev-dev libunwind-dev libsdl2-dev libgstreamer-plugins-bad1.0-dev protobuf-compiler libdbusxx
git clone --recursive https://github.com/gartnera/headunit.git
cd ~/headunit/mazda 
make
```
Copied over the headunit,json and wrapper to installer folder then to usb. Gunna try installing it on my car, Wish me luck boys!
If it works I'll update the readme and stuff for the script kiddies like me

**Comment by m3us** [comment]
@ryoncy  https://github.com/gartnera/headunit/wiki#instructions-to-compile-current-code-using-ubuntu-1604
@Trevelopment , I tested the code on my car and it works

**Pull request merged**
