### PR TITLE
Correctly Handle Transient Audio Focus Requests

### LINKED ISSUE #105: Nooo not another Bluetooth call bug!! Anything but that!
Hey @lmagder what you did with the audio focus is great work but I think from a comment in callbacks.cpp that you were anticipating this issue:
`else if (request.focus_type() == HU::AudioFocusRequest::AUDIO_FOCUS_GAIN_TRANSIENT) {
            audioMgrClient->audioMgrRequestAudioFocus(AudioManagerClient::FocusType::TRANSIENT); //assume navigation }`
That right there is not a great assumption to make because BTHF makes a request to gain transient audio focus as well.
So when a phone call comes in the AA stream takes audio focus first then gives it to BTHF but this causes the audio to stop playing and when the call is over audio does not start playing again.  The one exception to this is when you are in the entertainment context when you start up AA and playing external audio and have not switched to AA audio at all (that way AA does not try to take focus at the end of the call and the context change from phone to entertainment happens in the background).  
This is what the log entries look like when making a call (playing USB audio)
```
W: /home/mazda/headunit/hu/hu_aap.cpp:622: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 2
audioMgrRequestAudioFocus(2)
requestAudioFocus({"sessionId":23})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 13 for stream USB
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(2)
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"temporarilyLost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(0)
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"BTHF","streamModeName":"BTHF","newFocus":"gained","destination":"Cabin","focusType":"transient","streamType":"Telephony"}
Found audio sessionId 15 for stream BTHF
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"BTHF","streamModeName":"BTHF","newFocus":"lost","destination":"Cabin","focusType":"transient","streamType":"Telephony"}
Found audio sessionId 15 for stream BTHF
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
```
I tried to use the Notify signal handler and another flag variable when BTHF is the stream taking focus to stop the first audio focus change but by the time that signal hits it's already too late.  I will try some more things I have just been swamped because my company is running a prop auction for the show [Parks and Recreation](https://www.screenbid.com?headunit).

### PR DESCRIPTION
**Pull request by Trevelopment**
Just some small changes, AA doesn't need to capture transient requests to hear navigation also this messes up audio focus when dealing with BTFH.  This solves those things and you can see at how here #105 
Also, dont set FocusType::NONE on temporarilyLost focus event to allow AA music player to resume playing when the transient stream passes audio focus back or else the music pauses. 

fixes #105

### CODE REVIEW

**Comment by lmagder** [comment]
Does navigation still play over non-AA audio? I think AA still needs to take temporary focus to do this. There is no magic with nav, we are actually mixing it ourselves in the app :)

**Comment by Trevelopment** [comment]
I still need to test with google maps but so far with Waze I have found that navigation does still play if AA does not have audio focus.

**Comment by Trevelopment** [comment]
@lmagder II don't know if you've tried this build yet but  can confirm that at this commit all the audio focus transitions work correctly with GMaps, Waze, Phone Calls, MZD  and AA Audio Players the only exception is in the case of the output audio when using the voice command button if AA does not have audio focus.  Microphone still works fine regardless so It still works if you are listening to the USB audio or XM and  say like "navigate to work" and if you have the nav sounds on then the navigation will take transient focus and you will hear the end of the voice response too.   
So I was trying to rack my brain about why I never saw the navigation taking focus in the logs and how it still worked after this commit.  so I just told it to navigate me to work and drove around the block several times so that she would just constantly be yelling at me and looking at the log I noticed something.
```
KEY_T (any audio focus: 1 media focus: 1)
audioMgrReleaseAudioFocus()
requestAudioFocus({"sessionId":16})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(0)
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 16 for stream USB
W: /home/mazda/headunit/hu/hu_aap.cpp:622: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 3
audioMgrRequestAudioFocus(1)
requestAudioFocus({"sessionId":23})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 16 for stream USB
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(1)
W: /home/mazda/headunit/hu/hu_aap.cpp:622: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 4
audioMgrReleaseAudioFocus()
requestAudioFocus({"sessionId":16})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(0)
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 16 for stream USB
W: /home/mazda/headunit/hu/hu_aap.cpp:622: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 3
audioMgrRequestAudioFocus(1)
requestAudioFocus({"sessionId":23})
{}
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"USB","streamModeName":"USB","newFocus":"lost","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 16 for stream USB
AudioManagerClient::Notify signalName=audioFocusChangeEvent payload={"streamName":"MLENT","streamModeName":"MLENT","newFocus":"gained","destination":"Cabin","focusType":"permanent","streamType":"Media"}
Found audio sessionId 23 for stream MLENT
AudioFocusHappend(1)
W: /home/mazda/headunit/hu/hu_aap.cpp:622: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 4
audioMgrReleaseAudioFocus()
requestAudioFocus({"sessionId":16})
{}
```
I think you know what that means AUDIO_FOCUS_UNKNOWN should be AUDIO_FOCUS_NAVI 
So I also tried putting AA_CH_AU1 onto informationNavi and informationGenericso the good news is that they did take transient focus on the voice command button when AA didn't have focus but didn't play any sound, it would just go blank for a second.  Mic still worked fine.  So I was thinking there is another channel AA_CH_AU2 that looks like we may not use it, what is up with that? is that what the Navigation is set up on?  
I am also going to try some things to use the transient focus but store what had focus before BTHF so it can just request focus after.  That would pretty much solve that last transition because then we could capture the transient requests just fine.

**Comment by lmagder** [comment]
@Trevelopment I havent had a chance to mess with it much. I was trying to debug the GPS accuracy stuff and I think found a fix, but other than that haven't had much time.

Argh that's annoying it, feels like you are so close. When you were playing to informationNavi did you also call requestAudioFocus with a channel which maps to that stream? Maybe that's why it's playing nothing? If the code was switching to MLENT still the CMU mixer was using the other ALSA device maybe and you got silence?

Nice! we know AUDIO_FOCUS_UNKNOWN is finally. It's possible the AA doesn't actually do "transient" focus the enum actually could be like Media, Nav, and Voice Prompts for all we know. I have no idea about AA_CH_AU2  honestly. I know when we enabled it all the non-media sound started coming from the phone speaker (I know, that makes no sense since we are adding more audio to the car) so I was just like "Hmmmm, no" and turned it off and didn't investigate further.

**Comment by Trevelopment** [comment]
Well hey I got it buddy.  Its seems like the answer is so obvious once you figure it out its always just one tiny detail that you have to consider or path through the code to follow to find the spot where you need to handle the problem.   So we handle the audio focus request in MediaStart() and ignore the request from AudioFocusRequest() and it works like a charm perfect transitions no need to use a new asla device although that did kind of work in the end too (on "default" channel... didn't sound great).

**Comment by lmagder** [comment]
Awesome! I'm going to give this version a try. Keying on the mic is a good idea. I didn't think of that. 👍  I want to make sure other stuff like reading a text when clicking on the notification still works though since there is no mic involved (possibly it activates the mic anyway incase you respond so maybe it's fine?)

If not, it looks like there is a way of querying if a call is active via the com.jci.bthf DBus interface so maybe we can only ignore the AudioFocusRequest() if there is a call pending? Hopefully that state changes in CMU early enough. Maybe this is unnecessary though, need to test.

Also you still probably want to pass and track AudioManagerClient::FocusType::TRANSIENT for the NAVI focus. It actually doesn't do anything other than control if the Next/Prev track buttons are passed on or consumed based on what is set in currentFocus, it has nothing to do with the CMU audio stuff really. You would need to hit next track at the exact moment a navigation prompt is playing to notice the difference but I guess people could do it even if it's rare.

**Comment by Trevelopment** [comment]
Yea I saw a few places the code could be cleaned up a little bit too but I will leave that for you :grin:.  As it I now I tested every type of audio focus transition I could think of and they all worked fine but you're right I missed the incoming text notification.  Are there any other times AA needs/takes audio focus that i should consider?

**Comment by Trevelopment** [comment]
@lmagder I messed with querying the BTHF state back when I was looking at the first bluetooth call bug and on #16 I discuss it a little bit with @borconi.
The signals from the MZD are 
```
message CallStatus
{
  enum BTHF_STATE
  {
    BTHF_STATE_IDLE = 0;
    BTHF_STATE_INCOMING = 1;
    BTHF_STATE_ACTIVE = 2;
    BTHF_STATE_END = 3;
  }
  required BTHF_STATE bthf_state = 1
}
```
but I think the headunit values are
```
Phone_Status
{
enum Call status {
   - Inactive
   - in call
   - incoming
   - on hold
   - muted
   - conferenced
}
- Duration (int32)
- Thumbnail (bytearray)
- caller number
- caller id
```

**Comment by Trevelopment** [comment]
OK so one thing I found because I've been spamming the mic like crazy but the very first time you press the mic button you usually don't hear the first "beep" that kind of prompts you to say something, you know what I mean?  but by the time you say the command it will have taken focus and you will hear the response so it's not too big of a deal just a nit. Other than that it seems like it's all working pretty smoothly with a tiny bit of clean up it could work perfect.

**Pull request merged**
