### PR TITLE
Build cleanup and a few small fixes

### PR DESCRIPTION
**Pull request by lmagder**
I was seeing a problem on my car where the next track buttons didn't work due to the button up events never being sent. This is a pretty small change to the code, but it was difficult to reproduce the binaries in 0.93A release. However I was able to eventually, so I figured these changes and my fixes might help other people. I have the SSL change locally only, which was how I was able to test.

- I forked the [m3-toolchain](https://github.com/lmagder/m3-toolchain) repo and updated it to contain the libraries required to build the input_filter and headunit binaries
- I added git submodules to reference that and the mazda-connector to allow everything to built at once without extra setup, these probably should be changed to your forks if you want to merge this.
- Updated the Makefiles to track dependencies and not overlap between the Ubuntu and Mazda version
- Included the install files so they are versioned but omitting cmu_dataretrieval.up since I'm not sure if that is technically allowed to be redistributed. Same with sm.conf so people don't brick their cars accidentally
- Removed a bunch of unused files.

In terms of actual code changes:

- Reduced volume of audio streams to 40% so they approximately match the volume of other stuff like XM/FM otherwise AA is super loud by comparison.
- Scaled output to correct aspect ratio. The 800x480 screen seems to have non-square pixels based on the video files shipped with it since they are 800x480 but actually 16:9. AA doesn't seem to have a way to set pixel aspect ratio unfortunately so I changed the GStreamer pipeline to scale it to 751x480 to compensate. This adds small black bars on the sides but the image looks correct. Also scaled touch X to compensate.
- Refactored up the input event sending code into a util function shared by both versions and handle up/down events.
- Sent more buttons, the directions do nothing AFAIK, maybe we need report different capabilities at connection, but using the previously unused "Music" button for Play/Pause
- Fixed incorrect return value for delayedShouldDisplayTrue()

Anyway, I hope my changes are useful somehow, even if just for comparison. Great work on this project!

### CODE REVIEW

**Comment by gartnera** [comment]
Did you change anything in jni/* or did you just reformat that code. I know that code's messy, but I'm hesitant to reformat it because it destroys the version history.

I'll try and test your changes today.

**Comment by lmagder** [comment]
Not substantially. I added a hu_fill_button_message() function to try and reduce code duplication between the Ubuntu and Mazda versions, but that could be put somewhere else if preserving mergability of that code is important.

I think ideally it would awesome if the code could be refractored to use the protobuf library instead of bit bashing, but I could see why you would not want to do that since that would really mess up the history. :) I had some success writing proto files by adding names to the output of protoc --decode_raw

Thanks for taking a look.

**Comment by lmagder** [comment]
And by not substantially, I mean anything other than that function and enum is an accidental formatting change. Sorry, realised I was kind of vague.

**Comment by gartnera** [comment]
Yeah I've been meaning to look into redoing the original RE with actual proto bufs. Do you think you could share some examples of how you were doing that?

**Comment by lmagder** [comment]
Cool, yeah I think it would simplify the code a lot. Sure, I'll make an issue for the refactor and include some sample stuff when I get back to my PC with the code on it.

**Comment by gartnera** [comment]
Sorry for the delay. At this point, I don't really want to touch anything aside from mazda/main.c. If you want credit via the commit history, do you open an new PR with just the main.c changes?

If you don't care about credit, I can manually merge.

**Comment by lmagder** [comment]
Ok, I submitted a new PR. I made branch of my repo that more closely tracks the original to merge stuff easier.

**Pull request closed without merging**
