### PR TITLE
Fix Bluetooth Call Bug

### PR DESCRIPTION
**Pull request by Trevelopment**
Turns out the Bluetooth call issue had to do with the alsa config file asound.conf.  This fix copies a patched version of asound.conf fixing the clash between the media and telephony audio streams.

### CODE REVIEW

**Comment by lmagder** [comment]
Hi @Trevelopment! Thanks for looking into this! this is definitely one of the most reported issues so it's awesome you have found the root cause. 

I need to take a look closer at this before I'm read to merge it but a few things I noticed right off the bat: It would really nice to have the install script patch the alsa.conf instead of copying a whole already patched one. This is because we can never be sure what the initial state of the file is across different FW variants. 

I'm also not sure about your changes to the makefile. The -MD options is for generating the .d files required for the makefile dependency tracking so I don't think removing it has the effect you are hoping for. I think turning on optimization is a good idea (whoops 😊) but we were including symbols on purpose in the hope of having sensible crash logging.

**Comment by Trevelopment** [comment]
Hey @lmagder ok that would work it's the asound.conf file BTW but that would just be:
`sed -i 's/slave.pcm "tel_asymed"/slave.pcm "asymed"/g' /etc/asound.conf`
but to change it back would have to be coping the backup because  slave.pcm "asymed" is in that file multiple times.  And also I have a copy of 59.00.502 and my car had 55.00.753 and they both have asound.conf v1.0 so I dont think its going to change but I do suppose you are right.  I guess if you knew how to achieve the same result in the C++ code that would be cool too you need to change the value 'tel_asymed' to 'asymed' of pcm.telephonyGenericVol { slave.pcm "tel_asymed" } in asound.conf.  I'm not an expert in ALSA or C++ so you def know more than me about both.

As for the makefile I'm wondering, do you use the 22MB headunit binaries or do they come out smaller?  Because the optimized ones come out at about 6MB thats is almost 4 times smaller and I haven't seen a difference in performance.   And when you say you do that for crash logging I get that but most other people would probably want the smaller file since they wouldn't ever look at the crash logs anyway (actually most people wouldn't be able to tell the difference or care at all but you know.)  Also I wish I would have known that when I was trying to figure out this issue because I tried to read the core dumps but I couldn't even figure out how to.  So yea maybe its a good idea to have a dev and prod build so we could create the optimized file for production.

**Comment by Trevelopment** [comment]
Also There is a video focus issue when making or receiving a call and its like you lose video focus to the Mazda call screen but it seems frozen but if you have to hit the menu button you can use the controls and even reopen the app from the app menu and then you're in the AA call screen and it works fine.  I bet you know how to fix that one.

**Comment by Trevelopment** [comment]
Also you were right about patching asound.conf file because there are 2 variations depending on what country you are in there is RHD (Right Hand Drive) and LHD (Left Hand Drive)

**Comment by lmagder** [comment]
@Trevelopment Yeah probably mostly people don't need the 22MB file, I guess just maintaining different build variants is annoying in Makefiles and it's not like it being large is an issue, but fair point. 

I haven't had a chance to test this on my car yet but I I'm wondering: I'm also an ALSA noob so can you explain this fix a little more?  What does changing "tel_asymed" to "asymed" actually do? I ask since right now we are playing to the alsa "default" device, but looking the asound.conf there are many devices. I can't help but wonder if there is away to solve this without needing to modify the config file. Like for example playing to "entertainmentUsb" instead of default.

I noticed that default is defined like this 
`pcm.!default {
  type plug
  slave {
    pcm "asymed"
  }
}`

perhaps we are accidentally bypassing switching logic which is causing the car to get stuck in non-telephone mode? Following the chain of entertainmentUsb, it does also end up at asymed but perhaps there is hardcoded logic dealing with these devices somewhere else in the OS?

**Comment by Trevelopment** [comment]
I did understand what was going on and now that you explain it I definitely knew what I was doing.  This is how I thought of it while I was figuring out the issue .  I researched ALSA a whole lot so I got pretty knowledgeable.  I saw that telephony was getting "device or resource busy" error in the system logs when I would try to pinpoint the spot where I made the call and I realized that was the underlying issue.  I researched the error and a ALSA in general and it kept bringing me back the the config files.  So having learned about the plugins in ALSA I also knew about asynchronous streams by this point and dsnoop and I understood that there was a clash between the AA mic and the telephony mic input streams since I saw it wanted to use mic_hw directly in asound.conf and AA made its own mic channel that was running all the time.   

So I tried first to stop the mic channel but that did not work at all.  I don't know if its just that I'm not an expert at C++, I learned on Java and mostly have done web development the past 10 years so C++ is def not my strong point.  But after fruitless efforts of trying to kill or drop just the mic channel or stop it completely or make another channel that the telephony mic could use and I tried a few more things I have a branch where I expose the whole BTHF signal handlers and I tried doing all kind of things with that #79. 

So finally I just thought well what If I just let telephony use asymed and the dsnoop plugin with everyone else, I mean why does it even need to have that direct mic connection? there's probably a reason but f**k it ill try it anyway.  And Jesus Christ Monkey Balls it worked!  I was so crazy stoked cause that was like a several months from the time I started researching ALSA and getting into the headunit code.  So my understanding took quite a bit more research and learning to get to and was a much less eloquent than yours but I did understand what I was doing. 

So now onto if we can make this fix better I guess I didnt try not calling the mic in the constructor because I didn't know if that was something I could do.  What I tried to do was stop, drop, and shut em down open up shop on the mic channel wooaaah woooaaah it didn't work at aaaallllll.  haaaa anyways then I like tried to make the telephony stream be an audio stream but on the Bluetooth channel, that one just confused me.  I tried making another mic channel,. oh man I tried using the BTHF CallHandler and the different methods in the dbus to trigger things to happen like stopping the mic or opening a new stream or channel but I just think I wasn't doing those correctly because I don't really know exactly what the methods do.  Anyways when I figured out it was just 4 letters I had to remove in that config file my head almost exploded.  Then I tested it on a few people and they reported positively now I'm testing it on a few hundred people and haven't heard a negative report yet.  So I really showed my work on that one professor @lmagder. Check out #79 You don't have to merge it but you might want to that was the base commit I was using in my madness.

**Comment by lmagder** [comment]
Thanks! This makes sense. I modified the code to only open the mic when recording and it seems to fix the issue, which I think is better than modifying the car's ALSA config. I can make phone calls, but as you say the UI is weird and frozen. Ideally it stays in the AA UI the entire time but the car is stealing video focus back. I think you are on the right track with the BTHF stuff so I'll comment more there and close this one.

**Pull request closed without merging**
