### PR TITLE
Fix channel assignments and fix up hardware keys

### LINKED ISSUE #27: Channels mixed up
I have found a small problem in the original code, posted by Mike.

It took me a while to figure it out but eventually I did, Mike mixed up the channels when he reverse engineered the app, it's funny that it still works but that explains why we cannot get past the 6 taps limit even when the car is stopped. Here is what needs changing, I'm not submitting a commit because you might have changed things and I don't have the time to check the full code.

hu_aap.h should look like this:

```
 // #define AA_CH_SEN 1
  // #define AA_CH_VID 2
  // #define AA_CH_TOU 3  
  #define AA_CH_SEN 2
  #define AA_CH_VID 3
  #define AA_CH_TOU 1 
```

This means a few changes here and there mainly in hu_aap.c.
The aa_type_array should look like this:

```
 aa_type_ptr_t aa_type_array [AA_CH_MAX + 1] [3] [32] = {              // 0 - 31, 32768-32799, 65504-65535
                                                                        // Sync with hu_tra.java, hu_aap.h and hu_aap.c:aa_type_array[]
// Channel 0 Ctr Control:
    aa_pro_ctr_a00, aa_pro_ctr_a01, aa_pro_ctr_a02, aa_pro_ctr_a03, aa_pro_ctr_a04, aa_pro_ctr_a05, aa_pro_ctr_a06, aa_pro_all_a07, aa_pro_ctr_a08, aa_pro_ctr_a09, aa_pro_ctr_a0a, aa_pro_ctr_a0b, aa_pro_ctr_a0c, aa_pro_ctr_a0d, aa_pro_ctr_a0e, aa_pro_ctr_a0f,
    aa_pro_ctr_a10, aa_pro_ctr_a11, aa_pro_ctr_a12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,   //    a10, a11, a12, aa_pro_ctr_a13, aa_pro_ctr_a14, aa_pro_ctr_a15, aa_pro_ctr_a16, aa_pro_ctr_a17, aa_pro_ctr_a18, aa_pro_ctr_a19, aa_pro_ctr_a1a, aa_pro_ctr_a1b, aa_pro_ctr_a1c, aa_pro_ctr_a1d, aa_pro_ctr_a1e, aa_pro_ctr_a1f,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

// Channel 3 Tou TouchScreen:
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, aa_pro_all_a07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, aa_pro_tou_b02, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	
// Channel 1 Sen Sensor:
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, aa_pro_all_a07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, aa_pro_sen_b01, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

// Channel 2 Vid Video:
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, aa_pro_all_a07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    aa_pro_snk_b00, aa_pro_vid_b01, NULL, NULL, NULL, NULL, NULL, aa_pro_vid_b07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,



// Channel 4 Output Audio:
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, aa_pro_all_a07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    aa_pro_snk_b00, aa_pro_aud_b01, aa_pro_aud_b02, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

// Channel 5 Output Audio1:
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, aa_pro_all_a07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    aa_pro_snk_b00, aa_pro_aud_b01, aa_pro_aud_b02, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

// Channel 6 Output Audio2:
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, aa_pro_all_a07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    aa_pro_snk_b00, aa_pro_aud_b01, aa_pro_aud_b02, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

// Channel 7 Mic Audio:
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, aa_pro_all_a07, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, aa_pro_mic_b01, NULL, NULL, aa_pro_mic_b04, aa_pro_mic_b05, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

  };
```

You will need to make sure you adjust the sd_buf array as well in the same file.

Beside that here is the exact string used by Desktop Headunit Emulator to initiate the setup (this is sd_buf array in our file)

```
//Channel 1
0x0A, 0x0F, 0x08, 0x01, 0x22, 0x0B, 0x0A, 0x01, 0x54, 0x12, 0x06, 0x08, 0xA0, 0x06, 0x10, 0xE0, 0x03, 
//Channel 2
0x0A, 0x10, 0x08, 0x02, 0x12, 0x0C, 0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x0A, 0x0A, 0x02, 0x08, 0x0D, 
//Channel 3
0x0A, 0x15, 0x08, 0x03, 0x1A, 0x11, 0x08, 0x03, 0x22, 0x0D, 0x08, 0x01, 0x10, 0x02, 0x18, 0x00, 0x20, 0x00, 0x28, 0xA0, 0x01, 0x30, 0x00, 
//Channel 4
0x0A, 0x11, 0x08, 0x04, 0x1A, 0x0D, 0x08, 0x01, 0x10, 0x01, 0x1A, 0x07, 0x08, 0x80, 0x7D, 0x10, 0x10, 0x18, 0x01, 
//Channel 5
0x0A, 0x11, 0x08, 0x05, 0x1A, 0x0D, 0x08, 0x01, 0x10, 0x02, 0x1A, 0x07, 0x08, 0x80, 0x7D, 0x10, 0x10, 0x18, 0x01, 
//Channel 6
0x0A, 0x12, 0x08, 0x06, 0x1A, 0x0E, 0x08, 0x01, 0x10, 0x03, 0x1A, 0x08, 0x08, 0x80, 0xF7, 0x02, 0x10, 0x10, 0x18, 0x02, 
//Channel 7
0x0A, 0x0F, 0x08, 0x07, 0x2A, 0x0B, 0x08, 0x01, 0x12, 0x07, 0x08, 0x80, 0x7D, 0x10, 0x10, 0x18, 0x01, 
//Car data (name + version + driving position + etc)
0x12, 0x06, 0x47, 0x6F, 0x6F, 0x67, 0x6C, 0x65, 0x1A, 0x11, 0x44, 0x65, 0x73, 0x6B, 0x74, 0x6F, 0x70, 0x20, 0x48, 0x65, 0x61, 0x64, 0x20, 0x55, 0x6E, 0x69, 0x74, 0x22, 0x04, 0x32, 0x30, 0x31, 0x35, 0x2A, 0x24, 0x30, 0x35, 0x38, 0x32, 0x35, 0x32, 0x31, 0x66, 0x2D, 0x38, 0x37, 0x61, 0x63, 0x2D, 0x34, 0x30, 0x65, 0x64, 0x2D, 0x38, 0x61, 0x39, 0x39, 0x2D, 0x39, 0x36, 0x35, 0x39, 0x62, 0x61, 0x32, 0x65, 0x62, 0x37, 0x66, 0x33, 0x30, 0x00, 0x3A, 0x06, 0x47, 0x6F, 0x6F, 0x67, 0x6C, 0x65, 0x42, 0x11, 0x44, 0x65, 0x73, 0x6B, 0x74, 0x6F, 0x70, 0x20, 0x48, 0x65, 0x61, 0x64, 0x20, 0x55, 0x6E, 0x69, 0x74, 0x4A, 0x12, 0x32, 0x30, 0x31, 0x35, 0x2D, 0x30, 0x39, 0x2D, 0x31, 0x36, 0x2D, 0x32, 0x32, 0x35, 0x38, 0x37, 0x34, 0x35, 0x52, 0x09, 0x31, 0x2E, 0x30, 0x2D, 0x6C, 0x69, 0x6E, 0x75, 0x78, 0x60, 0x00,
 ```

Hope this helps.

### LINKED ISSUE #28: Rotary Input
Ok as promised on the main thread here is how you can get rotary input instead of touchscreen.

hu_aap.c the sd_buf should look like this
```
byte sd_buf2 []={0x00, 0x06, 
//Touch+input CHANNEL
//This commented line is touchscreen only, active line is rotary input: 0x0A, 0x0F, 0x08, 0x01, 0x22, 0x0B, 0x0A, 0x01, 0x54, 0x12, 0x06, 0x08, 0xA0, 0x06, 0x10, 0xE0, 0x03, 
0x0a, 0x12, 0x08, 0x01, 0x22, 0x0e, 0x0a, 0x0c, 0x01, 0x02, 0x04, 0x13, 0x14, 0x15, 0x16, 0x17, 0x54, 0x80, 0x80, 0x04,

// SENSOR CHANNEL
0x0A, 0x10, 0x08, 0x02, 0x12, 0x0C, 0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x0A, 0x0A, 0x02, 0x08, 0x0D,
//                       18,  12,     10,    2,    8,    1,  10,   2,     8,    10, 10,    2,    8,    13


// Video CHANNEL
0x0A, 0x15, 0x08, 0x03, 0x1A, 0x11, 0x08, 0x03, 0x22, 0x0D, 0x08, 0x01, 0x10, 0x02, 0x18, 0x00, 0x20, 0x00, 0x28, -96, 0x01, 0x30, 0x00, 
// MIC CHANNEL
0x0A, 4+4+7,0x08, AA_CH_MIC, 0x2A, 4+7, 0x08, 1,    0x12, 7,    0x08, -128, 0x7d, 0x10, 0x10, 0x18, 1,
// CAR DEFINITION
						
                        0x12, 4, 'E', 'm', 'i', 'l',//1, 'A', // Car Manuf          Part of "remembered car"
                        0x1A, 4, 'A', 'l', 'b', 'e',//1, 'B', // Car Model
                        0x22, 4, '2', '0', '1', '6',//1, 'C', // Car Year           Part of "remembered car"
                        0x2A, 4, '0', '0', '0', '1',//1, 'D', // Car Serial     Not Part of "remembered car" ??     (vehicleId=null)
                        0x30, 0,//0,      // driverPosition
						
                        0x3A, 4, 'E', 'm', 'i', 'l',//1, 'E', // HU  Make / Manuf
                        0x42, 4, 'H', 'U', '1', '5',//1, 'F', // HU  Model
                        0x4A, 4, 'S', 'W', 'B', '1',//1, 'G', // HU  SoftwareBuild
                        0x52, 4, 'S', 'W', 'V', '1',//1, 'H', // HU  SoftwareVersion
                        0x58, 0,//1,//1,//0,//1,       // ? bool (or int )    canPlayNativeMediaDuringVr
                        0x60, 0,//1,//0,//0,//1        // mHideProjectedClock     1 = True = Hide	*/	
						
//THE LAST 3 CHANNEL KEEP THEM HERE SO WE CAN EXCLUDE THEM IF NEED BE.
0x0A, 4+6+7, 0x08, AA_CH_AU2, 0x1A, 6+7, 0x08, 1,  0x10, 2, 0x1A, 7, 0x08, -128, 0x7d,         0x10, 0x10,   0x18, 1,
0x0A, 4+6+7, 0x08, AA_CH_AU1, 0x1A, 6+7, 0x08, 1,  0x10, 1, 0x1A, 7, 0x08, -128, 0x7d,         0x10, 0x10,   0x18, 1,
0x0A, 4+6+8, 0x08, AA_CH_AUD, 0x1A, 6+8, 0x08, 1,  0x10, 3, 0x1A, 8, 0x08, -128,   -9, 0x02,   0x10, 0x10,   0x18, 02,

};
```

Here comes the codes for buttons on rotary:
Enter:
WRITE: 80 01 08 c8 f9 80 fd ab 87 d3 c3 14 22 0a 0a 08 08 17 10 01 18 00 20 00 ;
WRITE: 80 01 08 90 c3 aa aa ac 87 d3 c3 14 22 0a 0a 08 08 17 10 00 18 00 20 00 ;

Simulates moving the rotary controller
Down:
WRITE: 80 01 08 e8 bb be ad de 87 d3 c3 14 22 0a 0a 08 08 14 10 01 18 00 20 00 ;
WRITE: 80 01 08 f8 93 d8 e9 de 87 d3 c3 14 22 0a 0a 08 08 14 10 00 18 00 20 00 ;

Right:
WRITE: 80 01 08 c0 c4 e5 86 ed 87 d3 c3 14 22 0a 0a 08 08 16 10 01 18 00 20 00 ;
WRITE: 80 01 08 c8 eb c3 bb ed 87 d3 c3 14 22 0a 0a 08 08 16 10 00 18 00 20 00 ;

Up:
WRITE: 80 01 08 a8 fc e1 de f8 87 d3 c3 14 22 0a 0a 08 08 13 10 01 18 00 20 00 ;
WRITE: 80 01 08 e8 fe db ba f9 87 d3 c3 14 22 0a 0a 08 08 13 10 00 18 00 20 00 ;

Left:
WRITE: 80 01 08 e8 f2 97 ab 86 88 d3 c3 14 22 0a 0a 08 08 15 10 01 18 00 20 00 ;
WRITE: 80 01 08 c8 dd d0 86 87 88 d3 c3 14 22 0a 0a 08 08 15 10 00 18 00 20 00 ;

Simulates pressing the side buttons available on some rotary controllers.
Soft right:
WRITE: 80 01 08 80 e6 80 f6 f6 88 d3 c3 14 22 0a 0a 08 08 02 10 01 18 00 20 00 ;
WRITE: 80 01 08 f0 b5 ec a2 f7 88 d3 c3 14 22 0a 0a 08 08 02 10 00 18 00 20 00 ;

Soft left:
WRITE: 80 01 08 80 f2 c7 a7 88 89 d3 c3 14 22 0a 0a 08 08 01 10 01 18 00 20 00 ;
WRITE: 80 01 08 f0 ef fc fc 88 89 d3 c3 14 22 0a 0a 08 08 01 10 00 18 00 20 00 ;

Simulates rotating the rotary controller left (counter-clockwise) or right (clockwise).

rotate left:
WRITE: 80 01 08 c8 e9 d6 bb 8a 8a d3 c3 14 22 0a 0a 08 08 15 10 01 18 00 20 00 ;
WRITE: 80 01 08 b0 c0 a6 88 8b 8a d3 c3 14 22 0a 0a 08 08 15 10 00 18 00 20 00 ;

Rotate right:
WRITE: 80 01 08 b0 b8 dd ed ce 8a d3 c3 14 22 0a 0a 08 08 04 10 01 18 00 20 00 ;
WRITE: 80 01 08 b0 d4 9e ee cf 8a d3 c3 14 22 0a 0a 08 08 04 10 00 18 00 20 00 ;

Simulates a fast spin of the rotary controller to the left (counter-clockwise) or right (clockwise).
Left:
WRITE: 80 01 08 c0 9b fb 8f 93 8b d3 c3 14 32 11 0a 0f 08 80 80 04 10 ff ff ff ff ff ff ff ff ff 01 ;
WRITE: 80 01 08 80 bc d0 e2 99 8b d3 c3 14 32 08 0a 06 08 80 80 04 10 01 ;

Right:
WRITE: 80 01 08 c8 a9 f2 87 b8 8b d3 c3 14 32 11 0a 0f 08 80 80 04 10 fb ff ff ff ff ff ff ff ff 01 ;
WRITE: 80 01 08 a0 c6 94 b3 be 8b d3 c3 14 32 08 0a 06 08 80 80 04 10 05 ;

### PR DESCRIPTION
**Pull request by izacus**
As per @borconi 's contribution in #27 and #28, this properly switches command channels for sensors and button inputs.

Major updates:

1. Switch channel order to sensors, video and touchscreen channels are now in proper order.
2. Update setup payload to signal availablitity of rotary input. This enables additional features in AA interface itself - searchbar is now available with on-screen keyboard and additional buttons in Google Maps interface.
4. Unify Mazda/Ubuntu key handling code and send proper payloads for keys and commander rotations.

Tested on Ubuntu only for now, since due to SSH issues I can't currently install input_filter on my M3.

TODO:

- [x] On Mazda itself, needs to signal rotate_left, rotate_right for commander turns. I need help from someone to figure out which keycodes are sent when the commander is rotated one step left or right.

Fixes #27. Fixes #28.

### CODE REVIEW

**Comment by izacus** [comment]
Ok, the rotate bindings should now be properly linked to the commander, just needs testing.

**Comment by borconi** [comment]
Now I'm eagerly waiting to see if the bluetooth fix will work for you.... not a mazda owner so cannot build/test myself... have a feeling that with this commits, you will get very very close to the original AA experience....

**Comment by izacus** [comment]
Closing this, reopening a new version.

**Comment by izacus** [comment]
Rebuilt in #33.

**Pull request closed without merging**
