### PR TITLE
Add Le Eco Vendor ID

### PR DESCRIPTION
**Pull request by memo-code**
Please add Le Eco Vendor ID to the list

### CODE REVIEW

**Comment by Jinmcx** [comment]
Never heard of LeCo but better add Xiaomi and Lenovo bigger brands =]

**Comment by memo-code** [comment]
I never heard of them neither until few weeks, after some research, I found that they are a big company in China that just open a US division in Silicon Valley earlier this year and making a lot of investment, like buying Vizio tv company, so looks like they are serious about coming to US market.

**Comment by memo-code** [comment]
Regardless of how important LeEco is, I have that phone and is working fine so far, so having the vendor ID added would be great for me, I hope this can be added :)

**Comment by gartnera** [comment]
Merged

**Pull request closed without merging**
